### ISSUE TITLE
user-submitted states

### ISSUE THREAD

**Issue by solaceten** [eventespresso/ee-packs-states-provinces#24]
On new EE4.6.4p there appears to be no ability for users to add new states.

I've switched themes and disabled all plugins - this is definitely a EE4 bug!  

I've also mentioned this in the following forum thread:
http://eventespresso.com/topic/country-state-what-is-the-expected-process/

**Comment by mnelson4** [comment]
Hi solaceten, ya somehow that missed and past testing. As a quickfix in 4.6.7 we added a filter "FHEE__EE_Billing_Attendee_Info_Form__state_field" that you can use to change the state input into a textfield.
So in 4.6.7 you can use that by placing the following code snippet into your theme's functions.php file:
```
add_filter( 'FHEE__EE_Billing_Attendee_Info_Form__state_field', 'state_text_field', 10, 1 );
function state_text_field( $original_field ) {
    return new EE_Text_Input( array( 'required' => true, 'html_class' => 'ee-billing-qstn'));
}
```


We expect to have the feature completely back in place soon, possibly in 4.6.8.

**Comment by solaceten** [comment]
OK thank you.  The only issue is I am currently on 4.6.6 and have not been notified of any update to 4.6.7 - is it public yet?  Will your snippet work on 4.6.6  ?  What about for Country field ?

**Comment by mnelson4** [comment]
We are just releasing 4.6.7 now, and no it won't work on 4.6.6.
The country field can be overridden to be a text field also using the filter with the same name but "country" in the name instead of "state", although you can also just activate all the countries already in your database then they'll appear in the country billing input.

**Comment by solaceten** [comment]
Hi 

I have updated to latest version (4.6.9) and have added the code mentioned by you above to the functions file in my theme - but this does nothing - I should clarify I am trying to achieve this on the REGISTRATION form.

Is there a filter for that?

**Comment by mnelson4** [comment]
No sorry this filter is only for the BILLING forms.

The easiest short-term fix for changing your REGISTRATION forms would be to
create a separate textfield state question, add it to your address
information question group and REMOVE the normal state question from the
question group.
Eg I created a new text state question:
https://docs.google.com/file/d/0B2KCao4zFjaxNlc5U0xKWHJ2NlU/edit?usp=drivesdk
and added it to the address information question group (replacing the old
normal state question):
https://docs.google.com/file/d/0B2KCao4zFjaxOVJ3V2NEdTVucjQ/edit?usp=drivesdk

The downside to this is that the new state question will be treated as an
extra registration form question, so it won't be autofilled into the
billing form etc. So this is only a quickfix until we re-add the ability to
add extra states back into the reg and billing forms

On Tue, Feb 17, 2015 at 8:27 PM, Sol <notifications@github.com> wrote:

> Hi
>
> I have updated to latest version (4.6.9) and have added the code mentioned
> by you above to the functions file in my theme - but this does nothing - I
> should clarify I am trying to achieve this on the REGISTRATION form.
>
> Is there a filter for that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventespresso/ee-packs-states-provinces/issues/24#issuecomment-74809956>
> .
>



-- 
Mike Nelson
Event Espresso Developer
eventespresso.com

**Comment by mnelson4** [comment]
FYi that we just merged the bugfix for the REGISTRATION form's state input into master and it should be released in the next day or so

**Comment by solaceten** [comment]
Thank the Lord !  Who would have thought it would be so hard to change a dropdown to a text field ! ?

If you would please be so kind as to update this when it is available, I will update immediately and throw you a high five if it works!

FYI the "add new state / country" option is still missing from the registration page.  It would simply take weeks to enable every country manually in the Countries select admin section.  The States Pack are missing many many countries (e.g Japan, China, Russia)

Perhaps you could make a case for adding an "enable all countries" in admin.  I also would argue the same should be said for states.

Thanks for your support on this matter.

**Comment by solaceten** [comment]
Hi

As an additional thought to my previous points; why is it even necessary to have country and state packs? Most country select form fields SIMPLY have the option to display all countries. It really seems an illogical and unnecessarily complicated step to have to manually add these in.

Why can't you simply grab one of these, and add it as an includes file that the form pulls the data from. Users may then modify it, if they so desire to remove countries they don't need / want.

http://www.freeformatter.com/iso-country-list-html-select.html

**Comment by eeteamcodebase** [comment]
Well we have all the COUNTRIES already (which is what's contained in that
link), it's the states that's the complicated part. But doing a quick
google I found an XML file that contains all the state info for basically
the entire world IN ENGLISH.
I think the issue is that the international folks will probably want them
in different languages anyways. And I think having ALL the states in ALL
the languages is the difficulty: it's a lot of data and a lot of work.
But I agree: it's something we could improve. I'll forward your
communication onto some others who have more say in it than I.

On Thu, Feb 19, 2015 at 5:08 PM, Sol <notifications@github.com> wrote:

> Hi
>
> As an additional thought to my previous points; why is it even necessary
> to have country and state packs? Most country select form fields SIMPLY
> have the option to display all countries. It really seems an illogical and
> unnecessarily complicated step to have to manually add these in.
>
> Why can't you simply grab one of these, and add it as an includes file
> that the form pulls the data from. Users may then modify it, if they so
> desire to remove countries they don't need / want.
>
> http://www.freeformatter.com/iso-country-list-html-select.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eventespresso/ee-packs-states-provinces/issues/24#issuecomment-75172590>
> .
>



-- 
Mike Nelson
Event Espresso Developer
eventespresso.com

**Comment by solaceten** [comment]
Hey, thanks for your response.

I think the issue is really very straight-forward.  Take a look at Woocommerce for inspiration as I believe they do it very well..

As you may know, the user is asked to select their country first (all enabled by default - no messing around in the admin to enable 300 countries or more!)  Then, once a country has been selected from the dropdown, the relevant states show for the selected country.  Very logical and easy to work with.

Since woocommerce is opensource - I am sure you could re-use and tweak their code ;-)

**Comment by joshfeck** [comment]
Event Espresso 4 uses this data store now for adding Country-related data:

https://github.com/astockwell/countries-and-provinces-states-regions
